# Generated by Django 3.2.2 on 2021-05-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('r_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('hashtag', models.CharField(max_length=64)),
                ('impact', models.IntegerField(default=0)),
            ],
        ),
    ]
